### PR TITLE
fix issue where the global RTK object got overwritten in the UMD files

### LINKED ISSUE #1761: React umd files under dist overwrites each other
Hi!

I had some problem with importing the umd version of RTK and RTK Query at the same time from a cdn.
Both files overwrites the global RTK object with this line in the bundled file: 
`(global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.RTK = {}));`

This results in that the last file that is loaded will overwrite the first file.

Affected files:
* @reduxjs/toolkit/dist/rtk-query.umd.js
* @reduxjs/toolkit/dist/query/rtk-query-react.umd.js

The issue can be seen here: https://codepen.io/Antignote/pen/gOxJJGB

Is there any solution to this or is it a bug?

### PR DESCRIPTION
**Pull request by Antignote**
fix #1761 where the global variable RTK gets overwritten by the other entries in the UMD build

### CODE REVIEW

File: packages/toolkit/scripts/build.ts [hunk 1]
```diff
@@ -97,18 +97,21 @@ const entryPoints: EntryPointOptions[] = [
...
     entryPoint: 'src/index.ts',
     extractionConfig: 'api-extractor.json',
+    globalName: 'RTK',
   },
   {
     prefix: 'rtk-query',
     folder: 'query',
     entryPoint: 'src/query/index.ts',
     extractionConfig: 'api-extractor.query.json',
+    globalName: 'RTK.QUERY',
```
Comment (markerikson) [inline packages/toolkit/scripts/build.ts:107]: :hand: Does this actually work? I think it would be safer/better to go with a `CONSTANT_CASE` name instead

File: packages/toolkit/scripts/build.ts [hunk 2]
```diff
@@ -97,18 +97,21 @@ const entryPoints: EntryPointOptions[] = [
...
   },
   {
     prefix: 'rtk-query-react',
     folder: 'query/react',
     entryPoint: 'src/query/react/index.ts',
     extractionConfig: 'api-extractor.query-react.json',
+    globalName: 'RTK.QUERY.REACT',
```
Comment (markerikson) [inline packages/toolkit/scripts/build.ts:114]: :hand: Let's use the same name for both RTKQ entries.  Users should only be loading one or the other anyway, and I think it's better to keep the same name either way.

**Review by markerikson — CHANGES_REQUESTED** [review]

File: packages/toolkit/scripts/build.ts (hunk 1 above)
Comment (Antignote) [reply packages/toolkit/scripts/build.ts:107]: Yes this works, it will generate this line in the UMD file: `(global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory((global.RTK = global.RTK || {}, global.RTK.QUERY = {})));`

Shall I keep it and just make the same change for RTKQ-React or do you want me to rename it as a new global object like `RTKQ`?

File: packages/toolkit/scripts/build.ts (hunk 2 above)
Comment (Antignote) [reply packages/toolkit/scripts/build.ts:114]: Yes, I'll fix this in the next commit and when we have settled where the entry will be placed in the global namespace.

File: packages/toolkit/scripts/build.ts (hunk 1 above)
Comment (markerikson) [reply packages/toolkit/scripts/build.ts:107]: Let's make both of these be `window.RTKQ`.

Comment (Antignote) [reply packages/toolkit/scripts/build.ts]: I've pushed new code to the PR

File: packages/toolkit/scripts/build.ts (hunk 2 above)
Comment (Antignote) [reply packages/toolkit/scripts/build.ts]: this is fixed in the latest commit

**Comment by markerikson** [comment]
Thanks!
