### PR TITLE
Fixed memory leak in rapid hook arg changing

### LINKED ISSUE #4267: Query entries aren't removed from state if arg changes while query is pending
Hey, I'm encountering a problem where queries never unsubscribe if arg changes while its pending. Here's a codesandbox to reproduce:

[https://codesandbox.io/p/sandbox/distracted-easley-6vnn6x](https://codesandbox.io/p/sandbox/distracted-easley-6vnn6x)

- The test query does nothing but resolve after 3 seconds. `keepUnusedDataFor` is set at zero (i also tested 1 with same results)

- The two buttons fast and slow change the speed at which the arg changes; 1 and 5 seconds respectively

Looking at the redux devtools: 

While the arg changes slowly everything works as intended: the last cached query is removed from state, keeping only one entry active.

However once the query starts changing args faster than its resolve period, a memory leak seems to appear where entries get added indefinietly and never get removed.

As a consequence, it's messing a bit with `onCacheEntryAdded`, since `cacheEntryRemoved` never resolves.

### PR DESCRIPTION
**Pull request by riqts**
Fixes #4267 

Tests failed in github actions referencing delay not being defined but I am not sure what to do to fix that, I did not add the import  for delay, simply referenced it. Any direction for that would be appreciated.

### CODE REVIEW

File: packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts [hunk 1]
```diff
@@ -100,6 +101,22 @@ export const buildCacheCollectionHandler: InternalHandlerBuilder = ({
         )
       }
     }
+
+    if (
+      queryThunk.fulfilled.match(action) ||
+      queryThunk.rejected.match(action)
+    ) {
+      const state = mwApi.getState()[reducerPath]
+      const queryCacheKey = action.meta.arg.queryCacheKey
```
Comment (phryneas) [inline packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:110]: This block only differs from the above in line 71, so I wonder if those could be consoldiated somehow 🤔

File: packages/toolkit/src/query/tests/buildHooks.test.tsx [hunk 2]
```diff
@@ -730,6 +730,60 @@ describe('hooks tests', () => {
...
+        )
+      }
+
+      render(<User />, { wrapper: storeRef.wrapper })
+      fireEvent.click(screen.getByTestId('fetchButton'))
+      fireEvent.click(screen.getByTestId('fetchButton'))
+      fireEvent.click(screen.getByTestId('fetchButton'))
+
+      await act(async () => {
+        await delay(1000)
```
Comment (phryneas) [inline packages/toolkit/src/query/tests/buildHooks.test.tsx:780]: As that hasn't been defined in this file yet, you'll have to define it somewhere at the top of the file

```ts
  function delay(ms: number) {
    return new Promise((resolve) => setTimeout(resolve, ms))
  }
```

File: packages/toolkit/src/query/tests/buildHooks.test.tsx [hunk 3]
```diff
@@ -730,6 +730,60 @@ describe('hooks tests', () => {
...
+
+      function User() {
+        const [fetchTest, { isFetching, isUninitialized }] =
+          pokemonApi.endpoints.getTest.useLazyQuery()
+
+        return (
+          <div>
+            <div data-testid="isUninitialized">{String(isUninitialized)}</div>
+            <div data-testid="isFetching">{String(isFetching)}</div>
+            <button data-testid="fetchButton" onClick={() => fetchTest(Math.random())}>
```
Comment (phryneas) [inline packages/toolkit/src/query/tests/buildHooks.test.tsx:767]: Maybe better something like `i++` instead of `Math.random` with `i` being a local `let` variable in the test.

File: packages/toolkit/src/query/tests/buildHooks.test.tsx (hunk 2 above)
Comment (aryaemami59) [reply packages/toolkit/src/query/tests/buildHooks.test.tsx:780]: I believe you should also just be able to re-use the `delay` function from `msw`:

```ts
import { delay } from 'msw'

await delay(1000)
```

File: packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts (hunk 1 above)
Comment (riqts) [reply packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts]: My newest commit should reflect these conditionals being turned into one. I am sure there's some TS trick to make the conditional simpler yet again if needed, but I am unsure of what that is off the top of my head.

```ts
 if (unsubscribeQueryResult.match(action) ||
      queryThunk.fulfilled.match(action) ||
      queryThunk.rejected.match(action)
    ) {
      const state = mwApi.getState()[reducerPath]
      let queryCacheKey: QueryCacheKey

      if (unsubscribeQueryResult.match(action)) {
        queryCacheKey = action.payload.queryCacheKey
      } else {
        queryCacheKey = action.meta.arg.queryCacheKey
      }
```

File: packages/toolkit/src/query/tests/buildHooks.test.tsx (hunk 3 above)
Comment (riqts) [reply packages/toolkit/src/query/tests/buildHooks.test.tsx]: Good idea, most recent iteration should reflect these changes :)

File: packages/toolkit/src/query/tests/buildHooks.test.tsx (hunk 2 above)
Comment (riqts) [reply packages/toolkit/src/query/tests/buildHooks.test.tsx]: My confusion here stems from the fact that it IS imported [here](https://github.com/reduxjs/redux-toolkit/blob/edafc36db93ca3dc6cfd8588f7e21fbb37e7aad2/packages/toolkit/src/query/tests/buildHooks.test.tsx#L39) and the test block directly below it uses it without problem.

Most likely I have just missed something painstakingly obvious, but I added a definition in the test block regardless.

**Comment by santirodriguezaffonso** [comment]
Is this going to be merged someday? 😭

**Comment by markerikson** [comment]
@santirodriguezaffonso : the PR has been up for only 3 days, and we're all busy atm. Please don't beg for things to be merged.

**Comment by EskiMojo14** [comment]
and in the meantime, you can click on the link in the codesandbox message to use the build that's already published.

File: packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts [hunk 4]
```diff
@@ -66,9 +67,18 @@ export const buildCacheCollectionHandler: InternalHandlerBuilder = ({
...
   ) => {
-    if (unsubscribeQueryResult.match(action)) {
+    if (unsubscribeQueryResult.match(action) ||
+      queryThunk.fulfilled.match(action) ||
+      queryThunk.rejected.match(action)
+    ) {
       const state = mwApi.getState()[reducerPath]
-      const { queryCacheKey } = action.payload
+      let queryCacheKey: QueryCacheKey
+
```
Comment (phryneas) [inline packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts:76]:
```suggestion
  const canTriggerUnsubscribe = isAnyOf(
    unsubscribeQueryResult.match,
    queryThunk.fulfilled,
    queryThunk.rejected
  )
  const handler: ApiMiddlewareInternalHandler = (action, mwApi) => {
    if (canTriggerUnsubscribe(action)) {
      const state = mwApi.getState()[reducerPath]
      const { queryCacheKey } = unsubscribeQueryResult.match(action)
        ? action.payload
        : action.meta.arg
```

Let's get this down in size even a little bit further.

File: packages/toolkit/src/query/tests/buildHooks.test.tsx [hunk 5]
```diff
@@ -730,6 +730,67 @@ describe('hooks tests', () => {
...
+              fetchUser
+            </button>
+          </div>
+        )
+      }
+
+      render(<User />, { wrapper: storeRef.wrapper })
+      fireEvent.click(screen.getByTestId('fetchButton'))
+      fireEvent.click(screen.getByTestId('fetchButton'))
+      fireEvent.click(screen.getByTestId('fetchButton'))
```
Comment (phryneas) [inline packages/toolkit/src/query/tests/buildHooks.test.tsx:784]:
```suggestion
      fireEvent.click(screen.getByTestId('fetchButton'))
      checkNumQueries(3)
```

Let's add a check showing that these are initially 3 and then go down to 1.

**Comment by phryneas** [comment]
Mark already said this, but please be a bit more patient. 

We are all doing this in our free time, and some things can take days, weeks or even months - it all depends on how many resources we have at any given time, given our day jobs and private lifes we have to balance with voluntary Open Source.

File: packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts (hunk 4 above)
Comment (riqts) [reply packages/toolkit/src/query/core/buildMiddleware/cacheCollection.ts]: Amazing! This is what I was trying to wrack my brain to come up with originally, but forgot to come back to it.
Newest commit should reflect this change.

File: packages/toolkit/src/query/tests/buildHooks.test.tsx (hunk 5 above)
Comment (riqts) [reply packages/toolkit/src/query/tests/buildHooks.test.tsx:784]: Good idea! Added the additional check

**Comment by riqts** [comment]
> Is this going to be merged someday? 😭

@santirodriguezaffonso 
Sorry buddy, you are being held back by my poor code quality! I require Lenz to do all the thinking for me, I am just his vessel to add code.

**Review by phryneas — APPROVED** [review]
No "poor code quality" here - libraries just need different code than applications. 
Your code was good from the start, we just have special requirements to keep bundle size down as a library :)

Thank you for the contribution!

**Comment by santirodriguezaffonso** [comment]
Thanks guys! You rock 🤟🏻
